### ISSUE TITLE
salesforce auth error?

### ISSUE THREAD

**Issue by shellSmart** [developerforce/reactive-salesforce-rest-angular-crud#1]
When running this tutorial, after config the connected app,  click login to salesforce, got following:
1.  Send to Salesforce login page, fill in username and password;
2.  localhost:9000 went back to original page. (Left: New Contact,   Right: "Login to Salesforce")
3. Activator UI logs show error, something like follows: 
   [error] play - Cannot invoke the action, eventually got an error:
java.lang.NullPointerException: null content
   [error] application -
! @6la374p0p - Internal server error, for (GET) [/contacts] ->
play.api.Application$$anon$1: Execution exception[[NullPointerException: null content]]
at play.api.Application$class.handleError(Application.scala:296) ~[na:na]
at play.api.DefaultApplication.handleError(Application.scala:402) [na:na]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [na:na]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [na:na]
at scala.Option.map(Option.scala:145) [na:na]
Caused by: java.lang.NullPointerException: null content
at play.mvc.Results$Status.<init>(Results.java:1326) ~[na:na]
at play.mvc.Results.ok(Results.java:171) ~[na:na]
at controllers.Application$2.apply(Application.java:42) ~[classes/:na]
at controllers.Application$2.apply(Application.java:39) ~[classes/:na]
at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:98) ~[na:na] 
........................

I think the error occurs inside the Oauth process.

**Comment by jamesward** [comment]
It looks like the results of the query might have been empty.  Can you verify you have contacts in your Salesforce instance?

**Comment by shellSmart** [comment]
Since I am using just a salesforce trial account, although I added contacts in my instance,  the call to Salesforce API actuall returned an "API_DISABLED_FOR_ORG" error.     Only able to see this error after add some debugging code in the SalesforceAPI.   

James, thanks very much for the answer.
